stages:
  - name: Build
    steps:
      - runScriptConfig:
          image: node:12-alpine
          shellScript: |-
            touch .env
            echo ${ENV_SALT} ${ENV_DB} ${ENV_COTE} ${ENV_GATEWAY}\
            | tr " " "\n" > .env
            cat .env
            npm install -g npm
            npm install
            node --version
            npm run build
            cp ./package*.json ./build
            mkdir ./build/swag
            cp --parents ./src/**/*swag.yaml ./build/swag
            cp --parents ./src/api/**/*swag.yaml ./build/swag
            ls -al ./build
        envFrom:
          - sourceName: env-salt
            sourceKey: dev-env
            targetKey: ENV_SALT
          - sourceName: env-db
            sourceKey: dev-env
            targetKey: ENV_DB
          - sourceName: env-cote
            sourceKey: dev-cote-key
            targetKey: ENV_COTE
          - sourceName: env-gateway
            sourceKey: dev-env-gateway
            targetKey: ENV_GATEWAY
        when:
          branch: develop
          event: [push]
      - runScriptConfig:
          image: node:12-alpine
          shellScript: |-
            touch .env
            echo ${ENV_SALT} ${ENV_DB} ${ENV_COTE} ${ENV_GATEWAY}\
            | tr " " "\n" > .env
            cat .env
            npm install -g npm
            npm install
            node --version
            npm run build
            cp ./package*.json ./build
            ls -al ./build
        envFrom:
          - sourceName: env-salt
            sourceKey: prod-env
            targetKey: ENV_SALT
          - sourceName: env-db
            sourceKey: prod-env
            targetKey: ENV_DB
          - sourceName: env-cote
            sourceKey: prod-cote-key
            targetKey: ENV_COTE
          - sourceName: env-gateway
            sourceKey: prod-env-gateway
            targetKey: ENV_GATEWAY
        when:
          branch: master
          event: [push]
  - name: Push
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: /test:${CICD_EXECUTION_SEQUENCE}
          pushRemote: true
          registry: gcr.io
  - name: Dev Deploy
    steps:
      - applyYamlConfig:
          path: ./deploy/dev-deployment.yaml
  - name: Prod Deploy
    steps:
      - applyYamlConfig:
          path: ./deploy/prod-deployment.yaml
